site_name: java-object-diff Documentation
repo_url: https://github.com/SQiShER/java-object-diff
pages:
- Home: index.md
- Using with Maven: maven.md
- Getting Started: getting-started.md
- User Guide:
  - User Guide: user-guide.md
- Merging: merging.md
