site_name: java-object-diff Documentation
repo_url: https://github.com/SQiShER/java-object-diff
pages:
- ['index.md', 'Home']
- ['maven.md', 'Using with Maven']
- ['getting-started.md', 'Getting Started']
- ['user-guide.md', 'User Guide', 'User Guide']
- ['merging.md', 'Merging']